# Generated by Django 3.2 on 2023-10-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chapter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('unit_id', models.FloatField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('knowledge_point_id', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.unit')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.knowledge_point'),
        ),
    ]
