# Generated by Django 3.2 on 2023-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20231009_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_id',
        ),
        migrations.RemoveField(
            model_name='knowledge_point',
            name='knowledge_point_id',
        ),
    ]
